// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Abort() {
  return window['go']['main']['AgentService']['Abort']();
}

export function GetConfig() {
  return window['go']['main']['AgentService']['GetConfig']();
}

export function GetMessages() {
  return window['go']['main']['AgentService']['GetMessages']();
}

export function ListSessions() {
  return window['go']['main']['AgentService']['ListSessions']();
}

export function LoadSession(arg1) {
  return window['go']['main']['AgentService']['LoadSession'](arg1);
}

export function NewSession() {
  return window['go']['main']['AgentService']['NewSession']();
}

export function Prompt(arg1) {
  return window['go']['main']['AgentService']['Prompt'](arg1);
}

export function Steer(arg1) {
  return window['go']['main']['AgentService']['Steer'](arg1);
}

export function SubmitPermission(arg1, arg2, arg3) {
  return window['go']['main']['AgentService']['SubmitPermission'](arg1, arg2, arg3);
}
