// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {desktop} from '../models';

export function Abort():Promise<void>;

export function GetConfig():Promise<desktop.UIConfig>;

export function GetMessages():Promise<Array<desktop.UIMessage>>;

export function ListSessions():Promise<Array<desktop.SessionSummary>>;

export function LoadSession(arg1:string):Promise<void>;

export function NewSession():Promise<string>;

export function Prompt(arg1:string):Promise<void>;

export function Steer(arg1:string):Promise<void>;

export function SubmitPermission(arg1:string,arg2:boolean,arg3:string):Promise<void>;
